### ISSUE TITLE
test_ntgbtminer.py failing

### ISSUE THREAD

**Issue by ngitzarak** [vsergeev/ntgbtminer#2]
Trying to understand the bitcoin mining algorithm, ran into this issue:
```
bob@orangepi2:~/ntgbtminer$ python2.7 test_ntgbtminer.py
..E.....E.
======================================================================
ERROR: test_block_mine (__main__.TestBlock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_ntgbtminer.py", line 148, in test_block_mine
    self.assertEqual(mined_block['hash'], test_vector)
TypeError: 'NoneType' object has no attribute '__getitem__'

======================================================================
ERROR: test_make_coinbase (__main__.TestTransaction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_ntgbtminer.py", line 58, in test_make_coinbase
    self.assertEqual(tx_make_coinbase(coinbase_script, address, value), test_vector)
TypeError: tx_make_coinbase() takes exactly 4 arguments (3 given)

----------------------------------------------------------------------
Ran 10 tests in 70.814s

FAILED (errors=2)
```
Running this on an armv7l processor

**Comment by ngitzarak** [comment]
Seems the timeout of 60 seconds was reached for test_block_mine.
Is it even supposed to run for more than a few seconds? I know that the processor I'm using is a slow one, but still?

**Comment by JustinTArthur** [comment]
I believe both errors are caused by the tests including the height header in the coinbase message instead of passing separately to the generation tx construction function.  Mining code itself seems correct. Addressed in pull #4.
